models:
  default:
    name: "llama-3.3-70b-versatile"
    temperature: 0.1
    max_retries: 2

  sql_generation:
    name: "llama-3.3-70b-versatile"
    temperature: 0.1

  image_generation:
    provider: "together"
    name: "black-forest-labs/FLUX.1.1-pro"
    width: 1024
    height: 768
    steps: 4
    n: 1
    response_format: "b64_json" 