models:
  default:
    name: "llama-3.3-70b-versatile"
    temperature: 0.1
    max_retries: 2

  sql_generation:
    name: "llama-3.3-70b-versatile"
    temperature: 0.1

  image_generation:
    provider: "openai"
    model: "dall-e-3"
    default_size: "1024x1024"
    default_quality: "standard"
    default_style: "vivid"
    max_retries: 2

  image_prompt:
    name: "llama-3.3-70b-versatile"
    temperature: 0.7
    max_retries: 2 